version: '3'
# define all services
services:
  # our service is called PHP Laravel ;-)
  php-laravel:
    # we want to use the image which is build from our Dockerfile
    build: 
      context: .
      dockerfile: Dockerfile
    image: merchant-onboarding
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    container_name: webapp-merchant
    #logging:
    #    driver: "json-file"
    #    options:
    #        max-file: 5
    #        max-size: 10m
    restart: always
    ports:
      - "86:80"
    privileged: true
    
    links:
      - mysql
      - redis
    # we mount the working dir into the container, handy for development
    volumes:
      - ./src/merchant-onboarding-portal:/var/www/html
      - ./laravel-que.conf:/etc/supervisor/conf.d/laravel-que.conf
      #- ./short-schedule.conf:/etc/supervisor/conf.d/short-schedule.conf
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    #network_mode: host
    #command: bash -c "rm /run/apache2/apache2.pid"

      
  mysql:
    image: mysql:5.7
    container_name: mysql-merchant
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=hadi123"
      - "MYSQL_DATABASE=merchant-onboarding-portal"
      - "MYSQL_PASSWORD=hadi123"
    ports:
      - "3310:3306"
    volumes:
    - ./dbdata:/var/lib/mysql

    #network_mode: host
   

  redis:
    image: redis:alpine
    container_name: redis-merchant  
      #environment:
      #  REDIS_PASSWORD=redis
    command: redis-server --appendonly yes --requirepass "redis"
    volumes:
      - ./redis:/data
    #ports:
    #  - "6379:6379"   
  
volumes:
  dbdata:

